# Generated by Django 4.2.2 on 2025-11-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='moneda',
            field=models.CharField(choices=[('CLP', 'Peso Chileno (CLP)'), ('USD', 'Dólar Estadounidense (USD)'), ('EUR', 'Euro (EUR)'), ('GBP', 'Libra Esterlina (GBP)'), ('ARS', 'Peso Argentino (ARS)'), ('MXN', 'Peso Mexicano (MXN)'), ('COP', 'Peso Colombiano (COP)'), ('PEN', 'Sol Peruano (PEN)'), ('BRL', 'Real Brasileño (BRL)')], default='CLP', max_length=3),
        ),
    ]
