# Generated by Django 4.2.2 on 2025-11-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_factura_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='rut',
            field=models.CharField(blank=True, max_length=20, verbose_name='RUT/DNI'),
        ),
    ]
