# Generated by Django 4.2.2 on 2025-11-17 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_factura_monto_iva_factura_monto_neto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='estado_sii',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
        migrations.AddField(
            model_name='factura',
            name='folio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='importado_sii',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='factura',
            name='monto_exento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='factura',
            name='tipo_dte',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
