# Generated by Django 4.2.2 on 2025-11-18 23:55

from django.db import migrations, models
from django.utils import timezone


def migrar_estados_antiguos(apps, schema_editor):
    """
    Migra los estados del sistema antiguo al nuevo sistema:
    - 'vencida' e 'impaga' → 'pendiente' con estado_cobranza apropiado
    """
    Factura = apps.get_model('core', 'Factura')
    hoy = timezone.now().date()

    for factura in Factura.objects.all():
        # Convertir estados antiguos a nuevos
        if factura.estado in ['vencida', 'impaga']:
            factura.estado = 'pendiente'

            # Calcular días vencidos
            dias_vencido = (hoy - factura.fecha_vencimiento).days

            # Asignar estado de cobranza según días vencidos
            if dias_vencido >= 90:
                factura.estado_cobranza = 'incobrable'
            elif dias_vencido >= 30:
                factura.estado_cobranza = 'mora'
            elif dias_vencido > 0:
                factura.estado_cobranza = 'vencida'
            else:
                # Por si acaso hay datos inconsistentes
                factura.estado_cobranza = 'vigente'

        elif factura.estado == 'pendiente':
            # Actualizar estado de cobranza para pendientes
            dias_vencido = (hoy - factura.fecha_vencimiento).days
            dias_para_vencer = (factura.fecha_vencimiento - hoy).days

            if dias_vencido >= 90:
                factura.estado_cobranza = 'incobrable'
            elif dias_vencido >= 30:
                factura.estado_cobranza = 'mora'
            elif dias_vencido > 0:
                factura.estado_cobranza = 'vencida'
            elif dias_para_vencer <= 7:
                factura.estado_cobranza = 'por_vencer'
            else:
                factura.estado_cobranza = 'vigente'
        else:
            # Pagadas y anuladas no tienen estado de cobranza
            factura.estado_cobranza = None

        factura.save()


def revertir_migracion(apps, schema_editor):
    """
    Revierte la migración al sistema antiguo
    """
    Factura = apps.get_model('core', 'Factura')

    for factura in Factura.objects.all():
        if factura.estado == 'pendiente' and factura.estado_cobranza in ['vencida', 'mora', 'incobrable']:
            factura.estado = 'vencida'
        factura.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_factura_estado_sii_factura_folio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='estado_cobranza',
            field=models.CharField(blank=True, choices=[('vigente', 'Vigente'), ('por_vencer', 'Por Vencer'), ('vencida', 'Vencida'), ('mora', 'En Mora'), ('incobrable', 'Incobrable')], default='vigente', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], default='pendiente', max_length=20),
        ),
        migrations.RunPython(migrar_estados_antiguos, revertir_migracion),
    ]
