# Generated by Django 4.2.2 on 2025-11-19 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_factura_estado_cobranza_alter_factura_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto ya pagado de la factura', max_digits=10),
        ),
        migrations.AddField(
            model_name='factura',
            name='monto_pendiente',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto que aún falta por pagar', max_digits=10),
        ),
    ]
