# Generated by Django 4.2.2 on 2025-11-21 00:41

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_monto_pagado_pendiente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(blank=True, default='', max_length=20, validators=[core.models.validar_rut_chileno], verbose_name='RUT/DNI'),
        ),
    ]
